name: Trigger Nightly Build

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      release:
        required: true
        type: string
        description: RHOAI Version

env:
  GITHUB_ORG: red-hat-data-services
  SOURCE_MAP: "src/config/releases.yaml"
  MIN_RELEASE: 216


jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      releases: ${{ steps.extract.outputs.releases }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Extract all versions
        id: extract
        run: |
          releases=$(yq -o json $SOURCE_MAP)
          releases=$(echo $releases | jq -r '.releases' | sed 's/ //g' | awk NF=NF RS= OFS=)
          if [[ "${{ github.event_name  }}" == "workflow_dispatch" ]]
          then
            releases=$(echo $releases | jq -c 'map(select(. == "${{ github.event.inputs.release }}"))'  | sed 's/ //g' | awk NF=NF RS= OFS=)
          fi
          
          #ensure the nightlies are not triggered for any non-konflux version
          min_release=${{ env.MIN_RELEASE }}
          filtered_releases=()
          while IFS= read -r release
          do
            version_number=${release/rhoai-/}
            version_number=${version_number/./}
            if [[ $version_number -ge $min_release ]]
            then
              filtered_releases+=("$release")
            fi
          done < <(echo $releases | jq -r '.[]')
          
          releases=$(jq -c -n '$ARGS.positional' --args "${filtered_releases[@]}" | sed 's/ //g' | awk NF=NF RS= OFS=)
          echo "This job will trigger nightlies for: $releases"
          echo "releases=$releases" >> $GITHUB_OUTPUT
  trigger-nightly:
    needs: [ setup ]
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        release: ${{ fromJSON(needs.setup.outputs.releases) }}
    steps:
      - name: Generate github-app token
        id: app-token
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: ${{ secrets.RHOAI_DEVOPS_APP_ID }}
          private_key: ${{ secrets.RHOAI_DEVOPS_APP_PRIVATE_KEY }}
      - uses: lasith-kg/dispatch-workflow@v2.0.0
        id: trigger-nightly
        name: Trigger Nightly
        with:
          dispatch-method: workflow_dispatch
          repo: rhods-operator
          owner: ${{ env.GITHUB_ORG }}
          ref: ${{ matrix.release }}
          workflow: trigger-nightly-operator-build.yaml
          token: ${{ steps.app-token.outputs.token }}
          workflow-inputs: '{}'
          discover: true
      - name: Display the Workflow Run Info
        run: |
          echo "run-id = ${{ steps.trigger-nightly.outputs.run-id }}"
          echo "run-url = ${{ steps.trigger-nightly.outputs.run-url }}"